package com.huymq.springeshop.entity;

public enum OrderStatus {
    UNPROCESSED, READY_TO_SHIP,PROCESSED, SHIPPED, COMPLETED, IN_CANCEL, CANCELLED
    // UNP, READY_TO_SHIP, PROCESSED, SHIPPED, COMPLETED, IN_CANCEL, CANCELLED
}
